CREATE TABLE books (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(1000) NOT NULL,
  author VARCHAR(1000) NOT NULL,
  isbn VARCHAR(100) NOT NULL,
  publishYear NUMERIC(4) NOT NULL,
  reserved BOOL NOT NULL DEFAULT FALSE
)

